CREATE TABLE Sales (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ProductName VARCHAR2(255) NOT NULL,
    Price NUMBER(10,2) NOT NULL,
    Quantity NUMBER NOT NULL,
    SaleDate DATE DEFAULT SYSDATE
);

SELECT * FROM Sales;